#!/usr/bin/env python3

import psycopg
import sys
import os

from psycopg.rows import dict_row

user = os.environ['POSTGRES_USER']
password = os.environ['POSTGRES_PASSWORD']
db = os.environ['POSTGRES_DB']

reference_genome = sys.argv[1]

if reference_genome not in ["grch37","grch38"]:
    print(f"Argument must be either 'grch37' or 'grch38'", file=sys.stderr)
    sys.exit(1)

# ARE YOU SURE?
if input("Are you sure you want to remove all the data in the database? (y/n) ") != "y":
    print(f"Error connecting to the database: {e}", file=sys.stderr)
    sys.exit(0)

# MAIN WORKFLOW

try:
    conn = psycopg.connect(
        user=user,
        password=password,
        host="postgres",
        dbname=db,
        autocommit=True )
except psycopg.Error as e:
   print(f"Error connecting to the database: {e}", file=sys.stderr)
   sys.exit(1)

cur = conn.cursor() 

print("Removing " + reference_genome + " from avalaible_genomes table... please wait..", file=sys.stderr)
try:
    cur.execute("DELETE FROM available_genomes WHERE genome = '" + reference_genome + "'") 
except psycopg.Error as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)

print("Removing ALL " + reference_genome + " genotypes from vcf_genotypes table... please wait..", file=sys.stderr)
try:
    cur.execute("DELETE FROM vcf_genotypes WHERE genome = '" + reference_genome + "'") 
except psycopg.Error as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)

print("Removing ALL " + reference_genome + " samples from vcf_samples table... please wait..", file=sys.stderr)
try:
    cur.execute("DELETE FROM vcf_samples WHERE genome = '" + reference_genome + "'") 
except psycopg.Error as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)

print("Finished!", file=sys.stderr)